#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx

sudo chown -R "$USER" /etc/nginx/sites-available
sudo chown -R "$USER" /var/www

echo "server {
	listen 80;
	listen [::]:80;
	server_name servingweb.tech;
	root /var/www/html;
	index index.nginx-debian.html;
}" > /etc/nginx/sites-available/default

sudo ufw allow 'Nginx HTTP'

sudo mkdir  /var/www/html/
sudo touch /var/www/html/index.html

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo nginx -t

sudo service nginx restart
