#!/usr/bin/env bash
# Installs Nginx, listening on port 80
# When querying Nginx at its root ''/'' with a GET request using ''curl''
#       returns ''Hello World!''
# ''redirect_me'' redirects to another predetermined page
# Has a custom 404 error page 

sudo apt-get -y update
sudo apt-get -y install nginx


# Granting permission to change files
sudo chown -R "$USER" /etc/nginx/sites-available
sudo chown -R "$USER" /var/www


# Configuring the port, redirection and error handling
echo "server {
	listen 80;
	listen [::]:80;
	server_name servingweb.tech;
	root /var/www/html;
	index index.nginx-debian.html;
	location /redirect_me {
		return 301 https://en.wikipedia.org/wiki/Nginx;
	}
	error_page 404 /error_404.html;
	location /404 {
		root /etc/html;
		internal;
	}
}" > /etc/nginx/sites-available/default


# Incoming HTTP fix
sudo ufw allow 'Nginx HTTP'


# Creating the string page
sudo mkdir  /var/www/html/
sudo touch /var/www/html/index.html


# Adding the string
echo "Hello World!" > /var/www/html/index.nginx-debian.html


# Setting up a custom 404 page message
echo -e "Ceci n'est pas une page" > /var/www/html/error_404.html


# Testing configurations
sudo nginx -t


sudo service nginx restart
